apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: paathshala
  name: deployment-flight
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-flight-service
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-flight-service
    spec:
      containers:
        - image: 615360450654.dkr.ecr.us-east-2.amazonaws.com/flight-service:latest
          imagePullPolicy: Always
          name: app-flight-service
          ports:
            - containerPort: 8081
              name: server
          env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: paathshala
  name: flight-service-svc
spec:
  ports:
    - port: 8081
  type: ClusterIP
  selector:
    app.kubernetes.io/name: app-flight-service
